/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'jge' at '7/26/15 3:12 PM' with Gradle 2.4
 *
 * @author jge, @date 7/26/15 3:12 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
